services:
  nuxt:
    build:
      context: .
      dockerfile: Dockerfile
      target: runner
    expose:
      - 3000
    environment:
      NODE_ENV: production
    networks:
      - internal

  caddy:
    image: caddy:latest
    ports:
       - "80:80"
       - "443:443"
    environment:
      - CF_API_TOKEN=${CF_API_TOKEN}
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - internal

volumes:
  caddy_data:
  caddy_config:

networks:
  internal:
    driver: bridge
      